POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQGdtYWlsLmNvbSIsImV4cCI6MTcxNTc4NzU3OCwidXNlcklkIjoxfQ.8pvCWU-vfdMYwtwpv3ot2QbKf6KCd6sLCEKYYviwWnk

{
  "name": "event1",
  "description": "event1 description",
  "dateTime": "2021-01-01T00:00:00Z",
  "location": "location1"
}

